### ISSUE TITLE
Incorrect collision + bounding boxes for blocks

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/PocketMine-MP#37]
### Issue description

Walking over bottom slabs, carpets and any other block with custom AxisAlignedBB causes 'Moved wrongly'
#blamedktapps

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP/issues/169

**Comment by thebigsmileXD** [comment]
This should be "Fixed" by the anti-movement-cheat option in the pocketmine.yml now.. Rename to Blocks Bounding Boxes.

**Comment by madcode15** [comment]
Seriously? A blame @dktapps?

You are a complete utter cretin.

First of all, this issue is completely nothing to do with dktapps code, he is just fixing what was left broken for half a year now.

Second, I'm surprise you're making these forks still. Instead of helping what created this community why don't you actually contribute to the real project? Did you know there is a great PR feature?

Maybe if dktapps left one day and you can't update the protocol on your ClearSky you would stop blaming him.

**Comment by thebigsmileXD** [comment]
@madcode15 Lol whats going on here 😆

**Comment by thebigsmileXD** [comment]
@madcode15 because i am not like i once was, i'll not ban you instantly so we can discuss this. I also thought about removing the tag here, since theres an option for movement checks. Sure i make these forks. This PocketMine **FORK** is here to simplyfy others life. Since @dktapps removed some necessary functions for block API and added new ones, its close to impossible creasting a plugin adding those. For example, EnderChest. It is directly bound to player nbt data + saving, you can't simply do this with plugins.

Also, since this is a FORK, not like Genisys or Elywing, or anything you want to name, we can simply update from upstream to keep it smooth and updated.

If you have problems with us, why do you even check this out?

You are simply hilarious. I got so much support on Twitter, writing to the devs of Mojang too, and i got a great, running server.

_**WHY I DON'T CONTRIBUTE TO THE ORIGINAL PROJECT?!**_
Wait, you haven't heard it yet? Because @dktapps is a complete moron.
He banned all my accounts for OPENING THIS ISSUE: https://github.com/pmmp/PocketMine-MP/issues/251

Also, i TRIED. I have (atleast) 6 accounts on github. Every time i noticed a mistake, i tried to give him a hint. Instead, you guessed it: got banned AGAIN.

So go, use some other core.

**Comment by thebigsmileXD** [comment]
One more thing, if you can read:
![image](https://cloud.githubusercontent.com/assets/8733998/22581871/7c188d8c-e9e3-11e6-998b-1b482c972e47.png)

**Comment by thebigsmileXD** [comment]
One more thing, if you can read:
![image](https://cloud.githubusercontent.com/assets/8733998/22581871/7c188d8c-e9e3-11e6-998b-1b482c972e47.png)
Also, he blocked me from the ITX chat on telegram+ gitter, on Twitter, this whole fork to mention hin etc. He wouldn't even notice in a slight that we mentioned him.

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/PocketMine-MP/issues/36

**Comment by thebigsmileXD** [comment]
#36 #35 That was #blamedktapps for by the way. Bugs INTRODUCED BY HIM.

**Comment by dktapps** [comment]
@madcode15 at least some of us have our facts straight, huh...

I wouldn't waste your time or keypresses, some people just never learn... they'll interpret and twist the truth however they like to get a picture they like.

Don't bother pinging me or replying, I won't see it. I only saw this because somebody brought it to my attention.

**Comment by thebigsmileXD** [comment]
How about reading, "brat"
> He wouldn't even notice in a slight that we mentioned/talked about him.

**Comment by thebigsmileXD** [comment]
"close" due to "fixed". dkt worked on it, idc.
